#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=16gb
#SBATCH --time=3:00:00
#SBATCH --job-name=simnibs
#SBATCH --mail-type=ALL
#SBATCH --mail-user=mphook@ufl.edu
#SBATCH --output=simnibs_%j.out

# . ./sysUtils.sh
# innitBashPaths

if [[ -z "$SYSNAME" ]]; then
echo environment not set.  run makeSysConfig.sh
exit
fi

if [ $SYSNAME == "hipergator" ]
then
  module load simnibs/4.0.0
  module load python/3.8
fi

set -e
charm --forceqform $1 $2 #$3 #Subject ID, T1, T2

cd m2m_$1


python $CODEDIR/Python/Simnibs/convert_mesh.py $1.msh
cd ..
