#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=16gb
#SBATCH --time=05:00:00
#SBATCH --job-name=THOMAS
#SBATCH --mail-type=ALL
#SBATCH --output=thomas_run_%j.out

if [[ -z "$SYSNAME" ]]; then
echo environment not set.  run makeSysConfig.sh
exit
fi

if [ $SYSNAME == "hipergator" ]
then
module load itk
module load ants
module load fsl
module load picsl
module load convert3d
fi

# Run THOMAS
/home/mphook/blue_butsonc/mphook/THOMAS/thomas_new/thomas_csh $1


#Left Side
echo "Left Side"

cp left/*Affine.mat ${PWD}
rm rigid0GenericAffine.mat
cp *.mat linear.mat

antsApplyTransforms -d 3 -i $CODEDIR/Bash/THOMAS/atlasA_CL_VPM.nii.gz -r left/crop* -o atlas_left.nii.gz -n GenericLabel -t [linear.mat,1] -t left/*InverseWarp.nii.gz

rm *.mat


#Right Side
echo "Right Side"

cp right/*Affine.mat ${PWD}
rm rigid0GenericAffine.mat
cp *.mat linear.mat

antsApplyTransforms -d 3 -i $CODEDIR/Bash/THOMAS/atlasA_CL_VPM.nii.gz -r right/crop* -o atlas_right_unflipped.nii.gz -n GenericLabel -t [linear.mat,1] -t right/*InverseWarp.nii.gz

rm *.mat


#Flip the right side to correct orientation
fslswapdim atlas_right_unflipped.nii.gz -x y z atlas_right.nii.gz
echo "Flip Right"

rm atlas_right_unflipped.nii.gz


echo "Resampling individual nuclei onto image"
#Left Nuclei Resampling
echo "Left Side"
cd left
mkdir Resample

for file in *-*.nii.gz
do
	antsApplyTransforms -d 3 -i $file -r ../$1 -o Resample/${file%.*.*}_resamp.nii.gz -n GenericLabel
done
rm Resample/san*

cd ../right
echo "Right Side"
mkdir Resample

for file in *-*.nii.gz
do
	antsApplyTransforms -d 3 -i $file -r ../$1 -o Resample/${file%.*.*}_resamp.nii.gz -n GenericLabel
done
rm Resample/san*

cd ..

echo "Resampling Atlases"

for file in atlas*
do
	antsApplyTransforms -d 3 -i $file -r $1 -o ${file%.*.*}_resamp.nii.gz -n GenericLabel
done

echo "Reconstructing Atlas CL"

if [ $SYSNAME == "hipergator" ]
then
module load python
fi

python $CODEDIR/Python/THOMAS/THOMAS_atlas_CL.py

echo "Done!"
