#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=16gb
#SBATCH --time=24:00:00
#SBATCH --job-name=freesurfer
#SBATCH --mail-type=ALL
#SBATCH --output=freesurfer_%j.out

# example call
# sbatch --mail-user=user@ufl.edu $CODEDIR/Bash/Freesurfer/fs_heatmap fs_pDummy T1_pre_scirun.nii.gz pDummy
# OR
# sbatch --mail-user=user@ufl.edu $CODEDIR/Bash/Freesurfer/fs_heatmap fs_pDummy T1_pre_scirun.nii.gz pDummy -FLAIR FLAIR_ACPC.nii.gz -FLAIRpial
# -FLAIR/FLAIRpial or -T2/T2pial
###
# TODO: figure out spaces in paths problem
# TODO: FS ID lookup table

if [[ -z "$SYSNAME" ]]; then
  echo environment not set.  run makeSysConfig.sh
  exit
fi


if [ $SYSNAME == "hipergator" ]
then
module load fsl
module load freesurfer/6.0.0
module load perl/5.20.0
fi

#SUBJECTS_DIR=/home/mphook/blue_butsonc/mphook/freesurfer/SimNIBS/FS_Subjects
export SUBJECTS_DIR="${FREESURFERDIR}"/FS_Subjects

rel_path1="SCIRun"
rel_path2="Connectome"
rel_path3="Segmentations/HCP"
rel_path4="Segmentations/Hotspot"
rel_path5="Segmentations/White_matter"


set -e

if [ -z "${4}" ]
then
echo recon-all -s "${1}" -i "${2}" -all -parallel -openmp 8
recon-all -s "${1}" -i "${2}" -all -parallel -openmp 8
else
echo recon-all -s "${1}" -i "${2}" -all -parallel -openmp 8 "${4}" "${5}" "${6}"
recon-all -s "${1}" -i "${2}" -all -parallel -openmp 8 "${4}" "${5}" "${6}"
fi
# comment out this line to make faster
# recon-all -s "${1}" -i "${2}" -all -parallel -openmp 8 -FLAIR "${4}" -FLAIRpial

m2m_id="$1"
subject=${m2m_id}
home="${PWD}"

subject_LO="$3"


#mv ${home}/${subject_id} $SUBJECTS_DIR

#Transform heat maps into patient space
echo $'\nTransforming Cortial Heat Maps to Patient Space **********************************************************************\n'
for hemi in lh rh
do
  call1="mri_surf2surf --srcsubject fsaverage --trgsubject ${subject} --trgsurfreg sphere.reg --hemi ${hemi} --sval ${SUBJECTS_DIR}/${hemi}.fsaverage.gm.PET_EEGFMRI_DWI_ZSCORE_4D_INTERSECTIONONLY_MEAN.proj-mid.sm10.5pcnt.min1cmsq.caudalmiddlefrontal.mgh --tval ${SUBJECTS_DIR}/${subject}/surf/${hemi}.thresh.mgh"
  echo $call1
  $call1
  
  call2="mri_surf2surf --srcsubject fsaverage --trgsubject ${subject} --trgsurfreg sphere.reg --hemi ${hemi} --sval ${SUBJECTS_DIR}/${hemi}.fsaverage.gm.PET_EEGFMRI_DWI_ZSCORE_4D_INTERSECTIONONLY_MEAN.proj-mid.sm10.posthresh.frontal.mgh --tval ${SUBJECTS_DIR}/${subject}/surf/${hemi}.heatmap.mgh"
  echo $call2
  $call2
  #Also adding HCP annotations to subject
  call3="mri_surf2surf --srcsubject fsaverage --trgsubject ${subject} --hemi ${hemi} --sval-annot ${SUBJECTS_DIR}/fsaverage/label/${hemi}.HCPMMP1.annot --tval ${SUBJECTS_DIR}/${subject}/label/${hemi}.HCPMMP1.annot"
  echo $call3
  $call3
done

# Convert heat maps to vtk
echo $'\nConvert Heat Maps to vtk **********************************************************************************************\n'
cd ${SUBJECTS_DIR}/${subject}/surf

for hemi in lh rh
do
  mris_convert -c ${hemi}.thresh.mgh ${hemi}.pial ${hemi}.thresh.vtk
  mris_convert -c ${hemi}.heatmap.mgh ${hemi}.pial ${hemi}.heatmap.vtk
done

#Convert thresh map to volume
echo $'\nCreate volume of Thresholded Heatmap **********************************************************************************\n'
mri_surf2vol --o thresh.nii.gz --subject ${subject} --so lh.pial lh.thresh.mgh --so rh.pial rh.thresh.mgh
mkdir -p ${DATADIR}/${subject_LO}/$rel_path4
mv thresh.nii.gz ${DATADIR}/${subject_LO}/$rel_path4
#Convert vtk to TriSurfField
echo $'\nConvert Heat Maps to .pts, .fac, and data *****************************************************************************\n'

if [ $SYSNAME == "hipergator" ]
then
module load python/3.10
fi

python ${CODEDIR}/Python/SCIRun/vtk_to_TriSurfField.py "${subject}"

mkdir -p ${DATADIR}/${subject_LO}/$rel_path1
mv *.pts ${DATADIR}/${subject_LO}/$rel_path1
mv *.fac ${DATADIR}/${subject_LO}/$rel_path1
mv *_data.txt ${DATADIR}/${subject_LO}/$rel_path1

#rm -r ${DATADIR}/${subject}/$rel_path1/*_threes.fac
cd ${home}

#HCP Volume Creation
echo $'\nCreate HCP Labelmap ***************************************************************************************************\n'
mri_aparc2aseg --s ${subject} --annot HCPMMP1 --o ${subject}_HCP.mgz


if [ $SYSNAME == "hipergator" ]
then
module load mrtrix
fi

mrconvert -datatype uint32 ${subject}_HCP.mgz ${subject}_HCP.mif -force
mkdir -p ${DATADIR}/${subject_LO}/$rel_path3
labelconvert ${subject}_HCP.mif ${CODEDIR}/Bash/Freesurfer/hcpmmp1_original.txt ${CODEDIR}/Bash/Freesurfer/hcpmmp1_subcortex.txt ${DATADIR}/${subject_LO}/${rel_path3}/HCP_FS.nii.gz

mkdir -p ${DATADIR}/${subject_LO}/$rel_path5
mrcalc ${subject}_HCP.mif 2 -eq ${DATADIR}/${subject_LO}/$rel_path5/WM_left.nii.gz -force
mrcalc ${subject}_HCP.mif 41 -eq ${DATADIR}/${subject_LO}/$rel_path5/WM_right.nii.gz -force

echo $'\n\n******************Done!****************\n\n'



