#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=16gb
#SBATCH --time=12:00:00
#SBATCH --job-name=freesurfer
#SBATCH --mail-type=ALL
#SBATCH --mail-user=mphook@ufl.edu
#SBATCH --output=freesurfer_%j.out


# slurm script wrapper for the bash script

./fs_heatmap_core.sh "$@"



